### ISSUE TITLE
Name and description fields too restrictive

### ISSUE THREAD

**Issue by stuart-storypark** [authsignal/terraform-provider-authsignal#25]
In the web GUI we can set rule names and descriptions that include spaces, hyphens, and for description can include other characters like <.

This module blocks us from doing so. For example a description of "Hello-World" gives the error:

`error description: body.description must conform to the following criteria: must match pattern "^[\w -!@#$%^&*(){}\[\]]{0,256}$" - pattern: ^[\w -!@#$%^&*(){}\[\]]{0,256}$`

Please allow the same range of characters at as the web ui. Even if only in the description field.

**Comment by stuart-storypark** [comment]
My appologies, it was actually a hyphen in the description that was causing my issue, not a space. I will edit the description

**Comment by LittleJono** [comment]
Hi Stuart,

Thanks for raising this. We have relaxed the validation for both rule names and descriptions to allow additional special characters. Here's the full list: ` !?@#$%^&*(){}:;"'<>,.+=/-_[]`. You don't need to update the Terraform provider version for this change to take affect. Please let me know if there's any other characters you'd like added.

**Comment by stuart-storypark** [comment]
Great, thanks, I will close this and open a new issue if I need any other characters.
