### ISSUE TITLE
Document acceptable values for fields

### ISSUE THREAD

**Issue by stuart-storypark** [authsignal/terraform-provider-authsignal#26]
When first implementing the module and writing the first action resource it was difficult to know what the acceptable values for some of the fields were.

It would be useful if it was clearer what the acceptable values for various fields like:

The verification fields.
In the action resource the default_user_action_result field.
In the rules resource the type field.

**Comment by LittleJono** [comment]
Hi Stuart,

Thanks for raising this. We will add the acceptable values into our provider documentation available on the Terraform registry. Is that where you would discover the values most easily?

In the interim please see our [documentation for our Management API](https://docs.authsignal.com/api-reference/management-api/overview) which is used by our Terraform provider and contains a list of the acceptable values for each field.

**Comment by stuart-storypark** [comment]
Sorry for the delayed response, I have been on vacation.

Yes, the Terraform registry was where I was looking.

Our workflow in this case was the dev team provisioned and setup rules for our staging environment using the web GUI. They then passed this to our infrastructure team to codify.

So I had the registry open in one window and the GUI into another.

**Comment by LittleJono** [comment]
Hi Stuart,

The latest release of the provider includes updates to the documentation which now has a list of allowed values for any field that requires an enum as the input.

**Comment by stuart-storypark** [comment]
Looks great, thanks!
