### ISSUE TITLE
Updating condition on existing rule gives a 'There is already another rule with priority: 0' error

### ISSUE THREAD

**Issue by stuart-storypark** [authsignal/terraform-provider-authsignal#28]
I am using version v1.3.1 of the module and v1.8.2 of the Terraform client.

I have a rule that was changed in the Web GUI. Only the condition on the rule changed.

Terraform is trying to return that rule to its codified state. Terraform correctly sees only the condition is different.

When trying to apply the change I get:

```
https://au.api.authsignal.com/v1/management/action-configurations/accessSupporthub/rules/<GUID> failed.
    status: 400 Bad Request
    error: invalid_configuration
    error description: There is already another rule with priority: 0
```

When I check in the web GUI the rules GUID matches the terraform error guid.

The rule is the first in the ordered list.

**Comment by LittleJono** [comment]
Hi Stuart, I have made some changes that will prevent this error from happening if the priority isn't changing. You won't need to update the version of the Authsignal provider, the change was made in the underlying API. You may still run into some of these priority errors if Terraform is trying to change priorities and the priority is already taken however.

**Comment by stuart-storypark** [comment]
Wonderful, thanks! I have re-run the apply and it successfully updated the condition. Appreciate the quick turnaround.
